print(f"Hola Bienvenido al programa de saludos")
nombre = input("Ingresa tu nombre: ")
print(f"Hola {nombre}")
apellido = input("Ingrese su apellido:")
print(f"hola, {nombre} {apellido}")
print(nombre * 3 + " " + apellido * 2)
cantidadNombre = len(nombre)
cantidadApellido = len(apellido)
print(f"tu nombre tiene {cantidadNombre} letras y tu apellido tiene {cantidadApellido} letras")
print(f"tu primera letra de tu nombre es: {nombre[0]} y la ultima es: {apellido[-1]}")
print(f"tu nombre en mayusculas es {nombre.upper()}")
print(f"tu apellido en mayusculas es: {apellido.upper()}")
print(f"tu nombre en minusculas es: {nombre.lower()}")
print(f"tu apellido en letras minusculas es: {apellido.lower()}")
print(f"Tu primera letra de tu nombre en mayuscula {nombre.title()}")
print(f"Tu primera letra de tu apellido en mayuscula es: {apellido.title()}")
print(f"tu nombre sin espacios es: {nombre.strip()}")
print(f"tu apellido sin espacios es: {apellido.strip()}")
print(f"tu nombre reemplazando la letra a por e es: {nombre.replace('a', 'e')}")
print(f"tu apellido reemplazando la letra a por e es: {apellido.replace('a', 'e')}")